### ISSUE TITLE
Adapt Makie text's line wrapping method

### ISSUE THREAD

**Issue by fatteneder** [fatteneder/MakieSlides.jl#10]
Native line wrapping was implemented with https://github.com/JuliaPlots/Makie.jl/pull/1819 and released with `Makie.jl v0.17.1`.

Not sure how to adapt it though, because the line wrapping magic seems to be only applied behind
```julia
function plot!(plot::Text{<:Tuple{<:Union{LaTeXString, AbstractVector{<:LaTeXString}}}})
...
end
```

(I think) we want to layout a `GlyphCollection` ourselves and pass that on to `text`. This way we can adjust text formatting on a word-by-word basis, which we need for bold, italic text emphases and later for syntax highligthing (see #6).

@ffreyer Since you authored Makie's line wrapping, do you think we can enhance the `text` interface to fit our needs here?
Or do you have another idea to get this to work with word-by-word styling?

**Comment by ffreyer** [comment]
For normal text it's applied in https://github.com/JuliaPlots/Makie.jl/blob/07f0763bcb8e990274aec5335deaa247bcf60229/src/layouting/layouting.jl#L93-L153.

I haven't taken a close look at how you implemented bold and italic, but I assume you just replace the font for relevant sections of text? If that's the case you should be able to add a `plot!()` function that adjusts the fonts and the string and passes that on to `text!`. Word wrapping should still work...

> Or do you have another idea to get this to work with word-by-word styling?

Afaik Makie does either the full string or each character. So if you have word by word you'd need to lower this to character by character

**Comment by fatteneder** [comment]
Ah, didn't see that, thanks.
So if it comes with `glyph_collection` then I think we just have to update to `0.17.1`, throw out the old code and it should just work™.

> ... but I assume you just replace the font for relevant sections of text?

Correct. As it is implemented for `Markdown.Paragraph`, I build up the `fontperchar, textsizeperchar, colorperchar` arrays myself based on the text elements type. In the end I forward it to `glyph_collection` and then call `text!(plot, glyphcollection)`.
So I think I am already doing it character-by-character wise as you suggest (and not word-by-word as I said above).
